Repository codenation-dev/squad-4-ad-python-2, pull requests merged in 2019-07, with the labels that each got.

#9 Alterar urls RESTful (sale, seller, plan) para plural
  api/urls.py
Labels: best-practices

#12 Instalar e configurar coverage
  .coveragerc
  Pipfile
  Pipfile.lock
  README.md
Labels: documentation

#20 GET Lista de vendedores mensal ordenados pelo valor da comissão
  api/urls.py
  api/views/monthly_comission.py
Labels: enhancement

#37 Test view `sales`
  api/tests/test_api_views/test_view_sale.py
  api/urls.py
  api/views/monthly_comission.py
Labels: test
